"""Project-wide constants for parsing, evaluation, and metrics."""

# Document statuses
DOCUMENT_STATUS_SUCCESS = "success"
DOCUMENT_STATUS_PARTIAL = "partial"
DOCUMENT_STATUS_FAIL = "fail"

DOCUMENT_STATUSES = {
    DOCUMENT_STATUS_SUCCESS,
    DOCUMENT_STATUS_PARTIAL,
    DOCUMENT_STATUS_FAIL,
}

# Field statuses
FIELD_STATUS_CORRECT = "correct"
FIELD_STATUS_INCORRECT = "incorrect"
FIELD_STATUS_MISSING = "missing"
FIELD_STATUS_NOT_APPLICABLE = "not_applicable"

FIELD_STATUSES = {
    FIELD_STATUS_CORRECT,
    FIELD_STATUS_INCORRECT,
    FIELD_STATUS_MISSING,
    FIELD_STATUS_NOT_APPLICABLE,
}

# Error reasons
ERROR_REASON_NONE = "none"
ERROR_REASON_SECTION_NOT_FOUND = "section_not_found"
ERROR_REASON_REPRESENTATIVE_NOT_FOUND = "representative_not_found"
ERROR_REASON_AUTHORITY_NOT_FOUND = "authority_not_found"
ERROR_REASON_REGISTER_ID_NOT_FOUND = "register_id_not_found"
ERROR_REASON_COUNT_MISMATCH = "count_mismatch"
ERROR_REASON_WRONG_NAME_SPLIT = "wrong_name_split"
ERROR_REASON_WRONG_CITY_ASSIGNMENT = "wrong_city_assignment"
ERROR_REASON_UNEXPECTED_LAYOUT = "unexpected_layout"
ERROR_REASON_PARSER_EXCEPTION = "parser_exception"

ERROR_REASONS = {
    ERROR_REASON_NONE,
    ERROR_REASON_SECTION_NOT_FOUND,
    ERROR_REASON_REPRESENTATIVE_NOT_FOUND,
    ERROR_REASON_AUTHORITY_NOT_FOUND,
    ERROR_REASON_REGISTER_ID_NOT_FOUND,
    ERROR_REASON_COUNT_MISMATCH,
    ERROR_REASON_WRONG_NAME_SPLIT,
    ERROR_REASON_WRONG_CITY_ASSIGNMENT,
    ERROR_REASON_UNEXPECTED_LAYOUT,
    ERROR_REASON_PARSER_EXCEPTION,
}